services:
  postgres:
    image: bitnami/postgresql:latest   # Evite usar 'latest', escolha uma versão estável
    container_name: postgres_task_manager
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    volumes:
      - postgres_data:/bitnami/postgresql   # Persistência dos dados
    restart: unless-stopped
    networks:
      - tasknet

volumes:
  postgres_data:

networks:
  tasknet:
    driver: bridge